### ISSUE TITLE
ngrok does not work with godaddy certs

### ISSUE THREAD

**Issue by listaction** [inconshreveable/ngrok#317] opened 2016-03-11 11:00 UTC
Related to : https://github.com/inconshreveable/ngrok/issues/56

I am still having this issue (using https://github.com/inconshreveable/ngrok using https://github.com/inconshreveable/ngrok/commit/f32dfef05845ae34763ec7bceecae544880bd82d) 

and the client is the one for osx downloaded today from the public site: ngrok.com

here's my ngrok client configuration:
server_addr: route.xyzz.com:443
trust_host_root_certs: true

and i started the client like this:
/ngrok http -config=/Users/kram/.ngrok 80
Tunnel Status                 reconnecting (x509: certificate signed by unknown authority)

[10:59:15 UTC 2016/03/11] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [pub:67a29b90] New connection from 49.248.228.19:31892
[10:59:15 UTC 2016/03/11] [WARN] (ngrok/log.(*PrefixLogger).Warn:87) [pub:67a29b90] Failed to read valid https request: remote error: bad certificate
[10:59:15 UTC 2016/03/11] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [pub:67a29b90] Closing

**Comment by inconshreveable** [comment] 2016-03-12 03:34
if anyone wants to jump in and help out, feel free, but closing as this is not a bug in ngrok

**Closed by inconshreveable** 2016-03-12 03:34 UTC

**Comment by listaction** [comment] 2016-03-15 16:21
why do you say this is not a bug in ngrok?

**Comment by listaction** [comment] 2016-03-15 16:22
the cert is valid and all other clients and servers seem to have no problem reading them.
