### ISSUE TITLE
Unknown, big memory-leak

### ISSUE THREAD

**Issue by KnutHelland** [inconshreveable/ngrok#109] opened 2014-04-04 08:02 UTC
Hello,

I don't know if it is a good idea to post this very unspecified bug report here. But I can't see any other issues about memleaks.

I'm running ngrok on my Raspberry Pi (http://weather.knuthelland.com/) and the ngrok-process eats memory for every http-request. After approx. 1000 (small) requests (I've not counted), the RaspPi goes down because ngrok uses 100% memory.

ngrok version = 1.6 (I think this is the latest?)

For now I've just created a daemon monitoring the process and restarting it when memory grows over 20%. If this bug is completely unknown, I can do some more research. Are there any easy way to dump a memory-report for `go tool pprof`?

**Comment by inconshreveable** [comment] 2016-03-12 03:03
this is fixed in ngrok 2.x. no plans to fix in 1.x, but will leave it open if anyone wants to fix

**Comment by niaiwomattt** [comment] 2016-11-28 02:57
This problem can be solved in the 2.x version? This is a serious problem.

**Comment by insekt** [comment] 2016-11-28 10:39
I'm still using 1.x version because of self-hosting option. So if it's not hard to fix then it would be great.

**Comment by dapao9999** [comment] 2017-02-20 10:01
i had this issue too,ngrok eat all of my memory

**Comment by TobiSchulz** [comment] 2017-02-21 09:18
ngrok v1 client eats all the memory at a 3gb fileupload on a 4gb machine so ngrok client crashed before upload complete. Is there anyway to fix it or should i not use ngrok for uploading larger files?

ngrok2 dosn´t got that bug, but on this machine i would like to use selfhosted ngrok.

**Comment by insekt** [comment] 2017-02-22 10:11
@dapao9999 @tobischulz 
you could try to disable web inspector in config file.
inspect_addr: disabled

It's work for me. I'm using version 1 because it allows selfhosting.

**Comment by tobischulz** [comment] 2017-02-22 13:29
@insekt thank you, that helps! but ngrok1 client still eating 2 gb on a 3 gb uploaded file. Is this a problem by the clients hdd? so the server is sending all the bytes and the client writes it to the hdd but can´t handle all the bytes are coming cause hdd wait?

**Comment by insekt** [comment] 2017-02-27 10:04
@tobischulz doesn't know :( could you describe you case in detail, I'll try to reproduce it.

**Comment by tobischulz** [comment] 2017-02-27 10:09
@insekt

- i´m using nextcloud on a local server with the ngrokv1 client. 
- ngrokv1 server is hosted on a digitalocean droplet (512mb). 
- Im uploading a file >= 3 gb to owncloud over ngrok url. 

You can see the ram is getting full on the local server until ngrokv1 client crashes. inspector is disabled by config file that let the client be alive some time longer till crash.

**Comment by insekt** [comment] 2017-02-28 15:52
@tobischulz will try to repeat your case

**Comment by cedricve** [comment] 2017-08-22 08:07
Having the same issue with forwarding a MJPEG stream (30FPS), it looks like some memory isn't released properly. I have hacked this with a restart policy running in the background (using @KnutHelland  workaround). This v1.x is highly instable.

**Comment by russorat** [comment] 2024-05-08 18:49
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Closed by russorat** 2024-05-08 18:49 UTC
Labels: bug
