### ISSUE TITLE
How can I update the request Host header?

### ISSUE THREAD

**Issue by loyalchow** [inconshreveable/ngrok#201] opened 2015-01-28 23:03 UTC
We'd like to update the ngrok client to send a custom Host header. We've tried doing this by changing the value of "req.Host" in ngrok/proto/http.go file, but the change seems to be ignored as the host header the eventual server sees is still from ngrok.com. What is the proper way to do this?

To give you some context, we need to create tunnels to several internal web sites running off the same ip and port. We do not have access to updating the ServerAlias config, and would like to pass the correct host header so apache knows which web site to return.

Thanks for your help! Cheers,

Loyal

**Comment by inconshreveable** [comment] 2015-01-29 18:41
Duplicate of https://github.com/inconshreveable/ngrok/issues/132

Feel free to email me if you'd like to test out the next version which solves this problem.

**Closed by inconshreveable** 2015-01-29 18:41 UTC

**Comment by jhabdas** [comment] 2015-12-23 15:08
`ngrok http -host-header=technologyadvice.com 80` is what I used to spoof the header to test CloudFlare after modifying my `/etc/hosts` file locally to point at the IP I got after doing a `@dig jeffery.ns.cloudflare.com www.technologyadvice.com`, in case that helps anyone.
