### ISSUE TITLE
NGROK Immediately Closing

### ISSUE THREAD

**Issue by InfernalPlank** [inconshreveable/ngrok#653] opened 2020-04-12 18:15 UTC
This has to be hands down one of the weirdest computing issues I've ran into. NGROK has worked _flawlessly_ for me for months now, yet all of a sudden, it legitimately just _stopped working_. No reason is given, but upon trying to do anything, the window terminates. I will attach a video.

_**My Problem:**_
[Steamable Link (Video / GIF)](https://streamable.com/pgd7au)

**Comment by RHQ-Rusty** [comment] 2020-04-13 04:10
@inconshreveable

**Comment by johnef** [comment] 2020-04-25 23:19
This happening with me too any idea whats happening here?

**Comment by underGhost** [comment] 2020-04-28 20:29
I've been getting this same issue on OSX Mohave. It just runs a `killed: 9` and the binary gets deleted. No idea why it happens.

If I restart my computer, and try to run it real fast, I can for the first few trieds before it gets deleted.

**Comment by RHQ-Rusty** [comment] 2020-04-28 23:40
I've had this problem for a while, and have seemingly had no hope in terms of support or solutions. I hope @inconshreveable replies eventually, but until then we'll most likely be waiting.

**Comment by MattDN93** [comment] 2020-05-13 13:22
+1 also seeing this issue in Mojave - tried the 32-bit and 64-bit binary, tried installing from Brew, no luck. Saw [this post](https://github.com/inconshreveable/ngrok/issues/649) which has a workaround using Docker but I'm also curious as to why it's happening. I tested with a Mac running Catalina and there were no issues. Hoping for a response here.

**Comment by RHQ-Rusty** [comment] 2020-05-19 03:19
@MattDN93 Not sure if the program auto-updated for a hotfix or what, but suddenly mine is working again... it is entirely possible it couldn't been an OS conflict.

**Comment by RHQ-Rusty** [comment] 2020-06-09 19:59
@inconshreveable any updates? Myself and a fair share of other users are experiencing this issue to no resolve. Additionally, I depend (well, did depend) on NGrok for quite a few things related to my work on a semi-consistent / day-to-day basis. Whatever the case is, I really hope it's fixed soon :)

@MattDN93 @underGhost @johnef - Any temporary fixes or workarounds been found for this issue yet?

**Comment by MattDN93** [comment] 2020-06-25 15:10
@RHQ-Rusty -> I used the workaround here: https://github.com/inconshreveable/ngrok/issues/649#issuecomment-626048166

**Comment by RHQ-Rusty** [comment] 2020-11-29 19:09
@MattDN93 @underGhost @johnef - Small Update for you Lads :)

I have found some very rudimentary / awkward ways of working around this issue. I've done a surprising amount of work investigating this issue and, while I was unable to reproduce it on other locally-located environments, I was able to reproduce it on my own environment.

The issue appears to be occurring due to shoddy process execution on a system level; whether this be a fault of NGrok or a poorly-managed Windows update, I don't know. If you notice, NGrok doesn't really give an error message or anything, it legitimately just _exits_. So, doing my digging, I found that somehow my PC had been spawning child processes of NGrok, preventing it from working. Whilst normally NGrok would call-back and tell you that only one session is supported on the free version (as this was my case), it was now not saying anything and immediately closing. Well, since this is locally detected (the PC sees multiple NGroks; NGrok servers don't even need to at this point). Upon force-killing the NGrok processes left stranded on my PC, I was able to **successfully start and use** NGrok for the first time in months. I restarted my PC, tested it again, and sure enough this was the issue.

I recommend introspectively looking through processes and making sure NGrok has 0 instances running when you wish to use it, making your new instance the _lone instance_ of NGrok on your machine. I also wrote an application that acts as a wrapper for NGrok and has dynamic process allocation so when you're done, NGrok 100% kills all NGrok-related or spawned processes. I'll consider touching it up and open-sourcing it soon.

Happy holidays, I hope this was able to help some! I'll leave this issue open if others need to ask any questions.

**Comment by VRsmore** [comment] 2021-01-09 00:51
I have been trying to fix this issue, what can I do

**Comment by ronisec** [comment] 2021-11-25 13:01
This is affecting me as well, I had to opt for the docker workaround. Specifically ran:

```sh
docker run -d --name ngrok wernight/ngrok ngrok http $(hostname):$LOCAL_PORT
docker exec -i ngrok curl localhost:4040/api/tunnels
```

**Comment by sdomi003** [comment] 2022-01-31 05:55
for my laptop, MacOS Catalina 10.15.7, I simply brew uninstall + reinstall and it started working again

**Comment by kumarabhirup** [comment] 2022-03-06 21:38
This issue didn't occur to me just until last month. Idk how to fix this, using `ngrok` from `npm i ngrok -g`.

**Comment by caseysoftware** [comment] 2022-09-26 20:53
This looks like it was locked on an old version of ngrok but hard to diagnose at this point.

These forums are unmonitored. For active support, check out our slack community: https://ngrok.com/slack

**Closed by caseysoftware** 2022-09-26 20:53 UTC

**Comment by mudassirsadiq** [comment] 2023-06-05 08:45
> @MattDN93 @underGhost @johnef - Small Update for you Lads :)
> 
> I have found some very rudimentary / awkward ways of working around this issue. I've done a surprising amount of work investigating this issue and, while I was unable to reproduce it on other locally-located environments, I was able to reproduce it on my own environment.
> 
> The issue appears to be occurring due to shoddy process execution on a system level; whether this be a fault of NGrok or a poorly-managed Windows update, I don't know. If you notice, NGrok doesn't really give an error message or anything, it legitimately just _exits_. So, doing my digging, I found that somehow my PC had been spawning child processes of NGrok, preventing it from working. Whilst normally NGrok would call-back and tell you that only one session is supported on the free version (as this was my case), it was now not saying anything and immediately closing. Well, since this is locally detected (the PC sees multiple NGroks), NGrok servers don't even need to at this point. Upon force-killing the NGrok processes left stranded on my PC, I was able to **successfully start and use** NGrok for the first time in months. I restarted my PC, tested it again, and sure enough this was the issue.
> 
> I recommend introspectively looking through processes and making sure NGrok has 0 instances running when you wish to use it, making your new instance the _lone instance_ of NGrok on your machine. I also wrote an application that acts as a wrapper for NGrok and has dynamic process allocation so when you're done, NGrok 100% kills all NGrok-related or spawned processes. I'll consider touching it up and open-sourcing it soon.
> 
> Happy holidays, I hope this was able to help some! I'll leave this issue open if others need to ask any questions.

**Comment by SitkaCharley** [comment] 2023-08-24 09:47
I've just got the same problem. ngrok version 3.3.2, Windows 10 Pro. After login into my ngrok account -> https://dashboard.ngrok.com/ , going to Tunnels -> Agents and deleting my session the ngrok works again. I.e. the cmd prompt doesn't get closed anymore right after starting the ngrok command.

**Comment by cawoodmonads** [comment] 2024-03-13 11:17
I'm having the same issue and my advice to the ngrok devs is, regardless of the specific cause of this error, don't start a new process. If users want a new process they can decide to do that (e.g. with `start ngrok http 3000` in windows) but when you force a new process this creates a new window and if it closes immediately we cannot even see what the error message is.

**Comment by cawoodmonads** [comment] 2024-03-13 11:26
I solved my issue by uninstalling `npm remove -g ngrok` and downloading ngrok.exe myself.

**Comment by Zapzatron** [comment] 2024-03-15 17:54
> This looks like it was locked on an old version of ngrok but hard to diagnose at this point. Download the latest version at https://ngrok.com/download
> 
> These forums are unmonitored. For active support, check out our slack community: https://ngrok.com/slack

![image](https://github.com/inconshreveable/ngrok/assets/100136305/f94f8479-b184-4d7d-ba1a-da1b645be17a)

**Comment by joaommmadureira** [comment] 2024-03-21 14:42
> @MattDN93 @underGhost @johnef - Small Update for you Lads :)
> 
> I have found some very rudimentary / awkward ways of working around this issue. I've done a surprising amount of work investigating this issue and, while I was unable to reproduce it on other locally-located environments, I was able to reproduce it on my own environment.
> 
> The issue appears to be occurring due to shoddy process execution on a system level; whether this be a fault of NGrok or a poorly-managed Windows update, I don't know. If you notice, NGrok doesn't really give an error message or anything, it legitimately just _exits_. So, doing my digging, I found that somehow my PC had been spawning child processes of NGrok, preventing it from working. Whilst normally NGrok would call-back and tell you that only one session is supported on the free version (as this was my case), it was now not saying anything and immediately closing. Well, since this is locally detected (the PC sees multiple NGroks), NGrok servers don't even need to at this point. Upon force-killing the NGrok processes left stranded on my PC, I was able to **successfully start and use** NGrok for the first time in months. I restarted my PC, tested it again, and sure enough this was the issue.
> 
> I recommend introspectively looking through processes and making sure NGrok has 0 instances running when you wish to use it, making your new instance the _lone instance_ of NGrok on your machine. I also wrote an application that acts as a wrapper for NGrok and has dynamic process allocation so when you're done, NGrok 100% kills all NGrok-related or spawned processes. I'll consider touching it up and open-sourcing it soon.
> 
> Happy holidays, I hope this was able to help some! I'll leave this issue open if others need to ask any questions.

I was having the same issue running nglok on my local enviroment and @InfernalPlank 's solution above worked perfectly for me, just by erasing current ngrok processes i could use ngrok in about 1 minute
